project_id = "dceldfybzabjlgudbzah"

[functions.organize-meeting]
verify_jwt = false

[functions.summarize-contributions]
verify_jwt = false

[functions.generate-whatsapp-message]
verify_jwt = false

[functions.auto-process-meeting]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false

[functions.summarize-for-pastor]
verify_jwt = false

[functions.seed-calendar-events]
verify_jwt = false

[functions.summarize-study]
verify_jwt = false

[functions.summarize-yearly-studies]
verify_jwt = false

[functions.generate-poster]
verify_jwt = false


