import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { PGlite } from '@electric-sql/pglite';

const db = new PGlite();
await db.exec(`
create role anon; create role authenticated;
create schema auth; create schema storage; create schema ipnc_private;
create table auth.users(id uuid primary key);
create table public.profiles(user_id uuid primary key references auth.users,full_name text,username text,active boolean);
create type public.app_role as enum('admin','diretoria','visualizador','pastor');
create table public.user_roles(user_id uuid,role public.app_role);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create function ipnc_private.actor_active() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.profiles where user_id=auth.uid() and active) $$;
create function ipnc_private.actor_has_role(wanted public.app_role) returns boolean language sql stable security definer set search_path='' as $$ select ipnc_private.actor_active() and exists(select 1 from public.user_roles where user_id=auth.uid() and role=wanted) $$;
grant usage on schema public,auth,ipnc_private,storage to anon,authenticated;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
alter table storage.objects enable row level security;
grant select,insert on storage.objects to authenticated;
grant select on public.profiles to authenticated;
`);
await db.exec(readFileSync(new URL('../supabase/migrations/20260928151725_public_treasury.sql', import.meta.url),'utf8'));
await db.exec(readFileSync(new URL('../supabase/migrations/20261005131159_treasury_approval_reconciliation.sql', import.meta.url),'utf8'));
const ids = Object.fromEntries(['admin','treasurer','outsider','inactive','fund','other','bank','income','expense','pending'].map(k=>[k,crypto.randomUUID()]));
await db.query(`insert into auth.users select unnest($1::uuid[])`,[[ids.admin,ids.treasurer,ids.outsider,ids.inactive]]);
await db.query(`insert into profiles select id,'Test','test',id<>$1 from auth.users`,[ids.inactive]);
await db.query(`insert into user_roles values($1,'admin'),($2,'admin'),($3,'diretoria'),($4,'visualizador')`,[ids.admin,ids.inactive,ids.treasurer,ids.outsider]);
await db.query(`insert into treasury_funds(id,name,abbreviation) values($1,'Test fund','T1'),($2,'Other','T2')`,[ids.fund,ids.other]);
await db.query(`insert into treasury_managers values($1,$2),($3,$2)`,[ids.treasurer,ids.fund,ids.inactive]);
const as = async (who,fn) => { await db.exec(`begin; set local role ${who?'authenticated':'anon'};`); await db.query(`select set_config('request.jwt.claim.sub',$1,true)`,[who||'']); try { const result=await fn(); await db.exec('commit'); return result; } catch(error) {await db.exec('rollback');throw error;} };
const insert = (id,fund,amount=10000,extra={}) => db.query(`insert into treasury_entries(id,fund_id,kind,amount_cents,occurred_on,person_name,description,status,payment_method,shirt_cents,monthly_fee_cents,per_capita_cents,bank_transaction_id,review_note) values($1,$2,$3,$4,'2025-02-10','Fixture only','Fixture only',$5,$6,$7,$8,$9,$10,$11) returning *`,[id,fund,extra.kind||'income',amount,extra.status||'pending',extra.payment_method||'pix',extra.shirt_cents||0,extra.monthly_fee_cents||0,extra.per_capita_cents||0,extra.bank_id||null,extra.note||'']);
const denied = fn => assert.rejects(fn,e=>e.code==='42501');

test('treasurer submits only own pending income; public cannot see pending, forge status or write', async()=>{
 await as(ids.treasurer,()=>insert(ids.income,ids.fund,10000,{shirt_cents:6000,monthly_fee_cents:3000,per_capita_cents:1000}));
 const forbiddenUpdate = await as(ids.treasurer,()=>db.query("update treasury_entries set status='confirmed',revision=2 where id=$1 returning id",[ids.income]));
 assert.equal(forbiddenUpdate.rows.length,0);
 await denied(()=>as(ids.treasurer,()=>db.query('insert into treasury_managers values($1,$2)',[ids.treasurer,ids.other])));
 await denied(()=>as(ids.treasurer,()=>insert(crypto.randomUUID(),ids.other)));
 await denied(()=>as(ids.treasurer,()=>insert(crypto.randomUUID(),ids.fund,10,{kind:'expense'})));
 await denied(()=>as(ids.treasurer,()=>insert(crypto.randomUUID(),ids.fund,10,{status:'confirmed'})));
 await denied(()=>as(ids.outsider,()=>insert(crypto.randomUUID(),ids.fund)));
 await denied(()=>as(ids.inactive,()=>insert(crypto.randomUUID(),ids.fund)));
 await denied(()=>as(null,()=>insert(crypto.randomUUID(),ids.fund)));
 assert.equal((await as(null,()=>db.query('select * from treasury_entries'))).rows.length,0);
 assert.equal((await as(ids.outsider,()=>db.query('select * from treasury_entries'))).rows.length,0);
 assert.equal((await as(ids.treasurer,()=>db.query('select * from treasury_entries'))).rows.length,1);
 const data=(await as(null,()=>db.query('select treasury_dashboard() data'))).rows[0].data;
 assert.equal(data.totals.balance_cents,0);
});
test('admin confirms once against a single bank credit and protects split/reserve accounting',async()=>{
 await as(ids.admin,()=>db.query(`insert into treasury_bank_transactions(id,reference,occurred_on,kind,amount_cents) values($1,'PIX-UNIQUE-001','2025-02-10','income',10000)`,[ids.bank]));
 await as(ids.admin,()=>db.query(`update treasury_entries set status='confirmed',bank_transaction_id=$1,revision=2 where id=$2 and revision=1`,[ids.bank,ids.income]));
 await assert.rejects(()=>as(ids.admin,()=>insert(crypto.randomUUID(),ids.fund,10000,{status:'confirmed',bank_id:ids.bank})),e=>e.code==='23514');
 await assert.rejects(()=>as(ids.admin,()=>db.query(`insert into treasury_bank_transactions(reference,occurred_on,kind,amount_cents) values(' pix-unique-001 ','2025-02-10','income',10000)`)),e=>e.code==='23505');
 await assert.rejects(()=>as(ids.admin,()=>insert(crypto.randomUUID(),ids.fund,50,{shirt_cents:40,monthly_fee_cents:40})),e=>e.code==='23514');
 await as(ids.admin,()=>insert(ids.expense,ids.fund,3000,{kind:'expense',status:'confirmed',payment_method:'cash',note:'Conferido no caixa',per_capita_cents:400}));
 await assert.rejects(()=>as(ids.admin,()=>insert(crypto.randomUUID(),ids.fund,1000,{kind:'expense',status:'confirmed',payment_method:'cash',note:'Conferido no caixa',per_capita_cents:700})),e=>e.code==='23514');
 const dashboard=(await as(null,()=>db.query('select treasury_dashboard() data'))).rows[0].data;
 assert.equal(dashboard.totals.balance_cents,7000); assert.equal(dashboard.totals.reserved_cents,600); assert.equal(dashboard.totals.available_cents,6400);
 const statement=(await as(null,()=>db.query('select treasury_statement($1) data',[ids.fund]))).rows[0].data;
 assert.equal(statement.entries[0].balance_after_cents,7000); assert.equal(statement.income_cents-statement.expense_cents,7000);
 assert.equal((await as(ids.admin,()=>db.query('select * from treasury_entry_audit'))).rows.length,3);
});
test('pending/rejected are separate, other-society reports and private attachments are protected',async()=>{
 await as(ids.treasurer,()=>insert(ids.pending,ids.fund,50));
 await as(ids.admin,()=>db.query(`update treasury_entries set status='rejected',review_note='Recebimento duplicado',revision=2 where id=$1`,[ids.pending]));
 const own=(await as(ids.treasurer,()=>db.query('select treasury_review_queue($1) data',[ids.fund]))).rows[0].data;
 assert.equal(own.entries[0].status,'rejected');
 await denied(()=>as(ids.outsider,()=>db.query('select treasury_report(2025,$1)',[ids.fund])));
 await denied(()=>as(ids.treasurer,()=>db.query('select treasury_report(2025,$1)',[ids.other])));
 await denied(()=>as(ids.treasurer,()=>db.query('select treasury_report(2025)')));
 await denied(()=>as(null,()=>db.query('select treasury_report(2025,$1)',[ids.fund])));
 const ownReport=(await as(ids.treasurer,()=>db.query('select treasury_report(2025,$1) data',[ids.fund]))).rows[0].data;
 assert.equal(ownReport.entries.length,2);
 const path=`${ids.income}/${crypto.randomUUID()}.pdf`;
 await as(ids.admin,()=>db.query(`insert into storage.objects(bucket_id,name) values('treasury-receipts',$1)`,[path]));
 const attachment=(await as(ids.admin,()=>db.query(`insert into treasury_attachments(entry_id,path,filename,mime_type) values($1,$2,'fixture.pdf','application/pdf') returning id`,[ids.income,path]))).rows[0];
 assert.equal((await as(ids.treasurer,()=>db.query('select * from treasury_attachments'))).rows.length,1);
 assert.equal((await as(ids.outsider,()=>db.query('select * from treasury_attachments'))).rows.length,0);
 assert.equal((await as(ids.outsider,()=>db.query('select * from storage.objects'))).rows.length,0);
 await denied(()=>as(ids.treasurer,()=>db.query(`insert into storage.objects(bucket_id,name) values('treasury-receipts','bad.pdf')`)));
 await denied(()=>as(null,()=>db.query('select * from treasury_attachments')));
 const managerArchive=await as(ids.treasurer,()=>db.query('update treasury_attachments set active=false where id=$1 returning id',[attachment.id]));
 assert.equal(managerArchive.rows.length,0);
 await as(ids.admin,()=>db.query('update treasury_attachments set active=false where id=$1',[attachment.id]));
 assert.equal((await as(ids.treasurer,()=>db.query('select * from treasury_attachments'))).rows.length,0);
 assert.equal((await as(ids.treasurer,()=>db.query('select * from storage.objects'))).rows.length,0);
 const archivedReport=(await as(ids.admin,()=>db.query('select treasury_report(2025,$1) data',[ids.fund]))).rows[0].data;
 assert.equal(archivedReport.attachments.length,0);
 assert.equal((await as(ids.admin,()=>db.query('select * from storage.objects'))).rows.length,1);
 await as(ids.admin,()=>db.query('update treasury_attachments set active=true where id=$1',[attachment.id]));
 const restoredReport=(await as(ids.treasurer,()=>db.query('select treasury_report(2025,$1) data',[ids.fund]))).rows[0].data;
 assert.equal(restoredReport.attachments.length,1);
 assert.equal((await as(ids.treasurer,()=>db.query('select * from storage.objects'))).rows.length,1);
 const audit=await as(ids.admin,()=>db.query("select new_record->'attachment'->>'active' active from treasury_entry_audit where new_record ? 'attachment' order by id"));
 assert.deepEqual(audit.rows.map(row=>row.active),['true','false','true']);
});
test('bank corrections keep audit and revision checks and cannot invalidate confirmed allocations',async()=>{
 await assert.rejects(()=>as(ids.admin,()=>db.query('update treasury_bank_transactions set amount_cents=9999,revision=2 where id=$1',[ids.bank])),e=>e.code==='23514');
 await assert.rejects(()=>as(ids.admin,()=>db.query("update treasury_bank_transactions set reference='OTHER-REF',revision=2 where id=$1",[ids.bank])),e=>e.code==='23514');
 await assert.rejects(()=>as(ids.admin,()=>db.query("update treasury_bank_transactions set kind='expense',revision=2 where id=$1",[ids.bank])),e=>e.code==='23514');
 await assert.rejects(()=>as(ids.admin,()=>db.query('update treasury_bank_transactions set amount_cents=12000 where id=$1',[ids.bank])),e=>e.code==='40001');
 assert.equal((await as(ids.treasurer,()=>db.query('update treasury_bank_transactions set amount_cents=12000,revision=2 where id=$1 returning id',[ids.bank]))).rows.length,0);
 await as(ids.admin,()=>db.query('update treasury_bank_transactions set amount_cents=12000,revision=2 where id=$1 and revision=1',[ids.bank]));
 const stale=await as(ids.admin,()=>db.query('update treasury_bank_transactions set amount_cents=13000,revision=2 where id=$1 and revision=1 returning id',[ids.bank]));
 assert.equal(stale.rows.length,0);
 const reconciliation=(await as(ids.admin,()=>db.query('select treasury_bank_reconciliation() data'))).rows[0].data.find(row=>row.id===ids.bank);
 assert.equal(reconciliation.remaining_cents,2000);
 const audit=await as(ids.admin,()=>db.query('select * from treasury_bank_audit where bank_id=$1 order by id',[ids.bank]));
 assert.equal(audit.rows.length,2);assert.equal(audit.rows[1].old_record.amount_cents,10000);assert.equal(audit.rows[1].new_record.amount_cents,12000);
 await denied(()=>as(ids.admin,()=>db.query('delete from treasury_bank_transactions where id=$1',[ids.bank])));
 assert.equal((await as(ids.outsider,()=>db.query('select * from treasury_bank_audit'))).rows.length,0);
 const unlinked=crypto.randomUUID();
 await as(ids.admin,()=>db.query("insert into treasury_bank_transactions(id,reference,occurred_on,kind,amount_cents) values($1,'WRONG-REFERENCE','2025-02-10','income',100)",[unlinked]));
 await as(ids.admin,()=>db.query("update treasury_bank_transactions set reference=' Correct Ref ',kind='expense',amount_cents=200,revision=2 where id=$1",[unlinked]));
 assert.equal((await as(ids.admin,()=>db.query('select reference from treasury_bank_transactions where id=$1',[unlinked]))).rows[0].reference,'CORRECTREF');
});
test('1005 confirmed entries, backdated carry-forward, filters and stale edits remain exact',async()=>{
 await as(ids.admin,()=>db.query(`insert into treasury_entries(fund_id,kind,amount_cents,occurred_on,person_name,description,status,payment_method,review_note) select $1,'income',1,'2024-01-01','Test','Bulk test','confirmed','cash','Conferido em teste' from generate_series(1,1005)`,[ids.fund]));
 const report=(await as(ids.treasurer,()=>db.query('select treasury_report(2025,$1) data',[ids.fund]))).rows[0].data;
 assert.equal(report.opening_cents,1005); assert.equal(report.entries.at(-1).balance_after_cents,8005);
 const data=(await as(null,()=>db.query(`select treasury_statement($1,'expense',null,'2025-01-01','2025-12-31',0,20) data`,[ids.fund]))).rows[0].data;
 assert.equal(data.entries[0].balance_after_cents,8005);
 const stale=await as(ids.admin,()=>db.query('update treasury_entries set amount_cents=20000,revision=2 where id=$1 and revision=1 returning id',[ids.income]));
 assert.equal(stale.rows.length,0);
 await denied(()=>as(ids.admin,()=>db.query('delete from treasury_entries where id=$1',[ids.income])));
 await as(ids.admin,()=>db.query('delete from treasury_managers where user_id=$1',[ids.treasurer]));
 await denied(()=>as(ids.treasurer,()=>insert(crypto.randomUUID(),ids.fund)));
});
test('one bank credit may be allocated across societies without exceeding the credit; reference spaces cannot duplicate it',async()=>{
 const a=crypto.randomUUID(),b=crypto.randomUUID(),bank=crypto.randomUUID();
 await as(ids.admin,()=>db.query("insert into treasury_funds(id,name,abbreviation) values($1,'Split A','SPLA'),($2,'Split B','SPLB')",[a,b]));
 await as(ids.admin,()=>db.query("insert into treasury_bank_transactions(id,reference,occurred_on,kind,amount_cents) values($1,' PIX SPLIT 002 ','2025-02-10','income',3000)",[bank]));
 await assert.rejects(()=>as(ids.admin,()=>db.query("insert into treasury_bank_transactions(reference,occurred_on,kind,amount_cents) values('PIXSPLIT002','2025-02-10','income',3000)")),e=>e.code==='23505');
 await as(ids.admin,()=>insert(crypto.randomUUID(),a,1000,{status:'confirmed',bank_id:bank,shirt_cents:600,monthly_fee_cents:400}));
 await as(ids.admin,()=>insert(crypto.randomUUID(),b,2000,{status:'confirmed',bank_id:bank,per_capita_cents:300}));
 await assert.rejects(()=>as(ids.admin,()=>insert(crypto.randomUUID(),b,1,{status:'confirmed',bank_id:bank})),e=>e.code==='23514');
 const reconciliation=(await as(ids.admin,()=>db.query('select treasury_bank_reconciliation() data'))).rows[0].data.find(row=>row.id===bank);
 assert.equal(reconciliation.allocated_cents,3000);assert.equal(reconciliation.remaining_cents,0);
});
test.after(async()=>{await db.close();});
